# Generated by Django 6.1.1 on 2026-09-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NEED_HELP', 'Need Help'), ('SOS', 'SOS')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('battery_level', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
